src/cs2610proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('hello/', include('hello.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += [path('hostname/', include('hostname.urls'))]
urlpatterns += [path('fib/', include('fib.urls'))]

src/fib/urls.py
from django.urls import path

from . import views

app_name = 'fib'
urlpatterns = [
    # /fib/fibAPI?n=20
    path('fibAPI', views.fibAPI, name='fibAPI'),

    # /fib/xhr
    path('xhr', views.xhr, name='xhr'),

    # /fib/fetch
    path('fetch', views.fetch, name='fetch'),

    # /fib/
    path('', views.index, name='index'),
]

src/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('highFive', views.highFive, name='highFive'),
    path('', views.index, name='index'),
]

src/hostname/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

src/fib/models.py
from django.db import models

# Create your models here.

src/hello/models.py
from django.db import models

class HighFiveCount(models.Model):
    slaps = models.IntegerField(default=0)


class HighFiveLog(models.Model):
    when = models.DateTimeField()
    who  = models.CharField(max_length=128)

src/hostname/models.py
from django.db import models

# Create your models here.

src/fib/views.py
from django.shortcuts import render
from django.http import JsonResponse


def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)


def fibAPI(request):
    # loop through the GET params and print them out
    for key in request.GET:
        print(f"\t{key} => {request.GET[key]}")

    if 'n' in request.GET:
        n = request.GET['n']
        if n.isnumeric():
            n = int(n)
            if n < 40:
                fib = fibonacci(int(n))
                response = {
                        'n': request.GET['n'],
                        'fibonacci': fib,
                        }
            else:
                response = {
                    'error': "Your 'n' parameter is too large",
                }

        else:
            response = {
                    'error': "Your 'n' parameter wasn't numeric :(",
                }
    else:
        response = {
                'error': 'You must supply a parameter "n"',
                }
    return JsonResponse(response)



def index(request):
    return render(request, 'fib/index.html')


def xhr(request):
    return render(request, 'fib/xhr.html')


def fetch(request):
    return render(request, 'fib/fetch.html')

src/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from time import strftime
from django.utils import timezone

from .models import HighFiveLog

def index(request):
    numbers = [7, 42, 1337]

    highFiveCount = HighFiveLog.objects.count()
    return render(request, 'hello/index.html',
        {
            'highFiveCount': highFiveCount,
            'now': strftime('%c'),
            'numbers': numbers,
        })


def highFive(request):
    log = HighFiveLog(when=timezone.now(), who = request.META['REMOTE_ADDR'])
    log.save()

    highfives = HighFiveLog.objects.all()
    return render(request, 'hello/highFive.html', { 'highFives': highfives })

src/hostname/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'hostname/index.html', { 'host':  request.get_host() })

src/fib/templates/fib/fetch.html
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
		<title>Fibonacci numbers</title>
		<link href="{% static 'fib/style.css' %}" rel="stylesheet">
	</head>

	<body>
        <div>
            <div class="stuff-box blue shadowed">
				<h2>Compute the Nth Fibonacci number via our awesome API and <code>fetch()</code></h2>
                <input type="number" id="fib" name="fib">
                <button type="button" onclick="calculate()">Calculate</button>
				<h3 id="result"></h3>
				<p id="duration"></p>
            </div>
			<div id="fibonacci-slider" class="stuff-box red shadowed">
				<label for="list-slider" id="list-label">Fib(0)</label>
				<input id="list-slider" type="range" min="0" max="50" value="0" oninput="fiblist(this)"/>
			</div>
			<div> <a href="{% url 'fib:index' %}">Back</a> </div>
        </div>

		<script type="text/javascript">

			let protocol = 'http';
			let hostname = 'localhost:8000';

			let calculate = function() {
				document.querySelector('#result').textContent =	'Okay, hang on while I think about this...';

				let fibReqUrl = `${protocol}://${hostname}/fib/fibAPI?n=${document.querySelector("#fib").value}`;

				let promiseStreamToJsonCallback = function(response) {
					console.log(`promiseStreamToJsonCallback was called after ${new Date() - before} milliseconds`);
					return response.json();
				}

				let promiseJsonProcessingCallback = function(json) {
					let duration = new Date() - before;
					console.log(`promiseJsonProcessingCallback was called after ${duration}ms`);
					console.log(json);
					document.querySelector('#result').textContent = `Fib(${json['n']}) = ${json['fibonacci']}`;
					document.querySelector('#duration').textContent = `Why, that only took ${duration} milliseconds!`; 
				};

				let before = new Date();
				let p0 = fetch(fibReqUrl);
				let p1 = p0.then(promiseStreamToJsonCallback);
				let p2 = p1.then(promiseJsonProcessingCallback);
			}


			var fiblist = function(n) {
				// Remove an existing Fibonacci list
				let fiblist = document.querySelector('div.fib-list');
				if (fiblist) {
					fiblist.remove();
				}
				document.querySelector('#list-label').textContent = `Fib(${n.value})`;
				let list = fiblistHelper(Number.parseInt(n.value));
				document.querySelector('#fibonacci-slider').appendChild(list);
			}

			var fiblistHelper = function(n)  {
				// create a div that is .fib-list
				var div = document.createElement('div');
				div.setAttribute('class', 'fib-list');

				// fill it with a list of numbers
				for (var i = 0, a = 0, b = 1; i <= n; ++i, b = a + b, a = b - a) {
					var num = document.createElement('div');
					num.setAttribute('class', 'fib-item');
					var p = document.createElement('p');
					p.textContent = a;
					num.appendChild(p);
					div.appendChild(num);
				}

				return div;
			}

		</script>
	</body>
</html>

src/fib/templates/fib/index.html
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
		<title>Fibonacci numbers</title>
		<link href="{% static 'fib/style.css' %}" rel="stylesheet">
	</head>

	<body>
        <div>
            <div class="stuff-box yellow shadowed">
				<h2>Compute the Nth Fibonacci number with your choice of AJAX APIs</h2>
				<ul>
					<li><a href="{% url 'fib:xhr' %}">XMLHttpRequest</a></li>
					<li><a href="{% url 'fib:fetch' %}">fetch() and Promises</a></li>
				</ul>
            </div>
        </div>

	</body>
</html>

src/fib/templates/fib/xhr.html
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
		<title>Fibonacci numbers</title>
		<link href="{% static 'fib/style.css' %}" rel="stylesheet">
	</head>

	<body>
        <div>
            <div class="stuff-box green shadowed">
				<h2>Compute the Nth Fibonacci number via our awesome API and <code>XMLHttpRequest</code></h2>
                <input type="number" id="fib" name="fib">
                <button type="button" onclick="calculate()">Calculate</button>
				<h3 id="result"></h3>
				<p id="duration"></p>
            </div>
			<div id="fibonacci-slider" class="stuff-box red shadowed">
				<label for="list-slider" id="list-label">Fib(0)</label>
				<input id="list-slider" type="range" min="0" max="50" value="0" oninput="fiblist(this)"/>
			</div>
			<div> <a href="{% url 'fib:index' %}">Back</a> </div>
        </div>

		<script type="text/javascript">

			let protocol = 'http';
			let hostname = 'localhost:8000';

			let calculate = function() {
				document.querySelector('#result').textContent =	'Okay, hang on while I think about this...';

				let fibReqUrl = `${protocol}://${hostname}/fib/fibAPI?n=${document.querySelector("#fib").value}`;

				let fibReq = new XMLHttpRequest();
				fibReq.open('GET', fibReqUrl);
				fibReq.responseType = 'json';
				fibReq.onload = function() {
					let json = fibReq.response;
					let duration = new Date() - before;
					console.log(`The XHR callback received a result after ${duration}ms`);
					console.log(json);
					document.querySelector('#result').textContent = `Fib(${json['n']}) = ${json['fibonacci']}`;
					document.querySelector('#duration').textContent = `Why, that only took ${duration} milliseconds!`; 
				}
				let before = new Date();
				fibReq.send();
			}


			var fiblist = function(n) {
				// Remove an existing Fibonacci list
				let fiblist = document.querySelector('div.fib-list');
				if (fiblist) {
					fiblist.remove();
				}
				document.querySelector('#list-label').textContent = `Fib(${n.value})`;
				let list = fiblistHelper(Number.parseInt(n.value));
				document.querySelector('#fibonacci-slider').appendChild(list);
			}

			var fiblistHelper = function(n)  {
				// create a div that is .fib-list
				var div = document.createElement('div');
				div.setAttribute('class', 'fib-list');

				// fill it with a list of numbers
				for (var i = 0, a = 0, b = 1; i <= n; ++i, b = a + b, a = b - a) {
					var num = document.createElement('div');
					num.setAttribute('class', 'fib-item');
					var p = document.createElement('p');
					p.textContent = a;
					num.appendChild(p);
					div.appendChild(num);
				}

				return div;
			}

		</script>
	</body>
</html>

src/hello/templates/hello/highFive.html
{% load static %}
<html>
    <head>
        <title>Erik's sinister #HighFive counter</title>
		<link rel="stylesheet" href="{% static 'hello/style.css' %}" />
    </head>
    <body>
		<div class="blue stuff-box">
			Visit http://144.39.173.24/hello/highFive
		</div>
        <div class="yellow stuff-box">
            <p class="big">#HighFive!</p>
			<p class="medium">Number of high fives given by this site: {{ highFives.count }}</p>
			{% if highFives %}
			<ol>
				{% for slap in highFives %}
				<li> {{ slap.when }} - {{ slap.who }}</li>
				{% endfor %}

			</ol>
			{% endif %}
        </div>

        <p><a href=".">Back</a></p>
    </body>
</html>

src/hello/templates/hello/index.html
{% load static %}
<html>
    <head>
        <title>How I shall take over the world</title>
		<link rel="stylesheet" href="{% static 'hello/style.css' %}"/>
    </head>
    <body>
        <div class="red stuff-box">
            <div class="big">Hello, world!</div>
            <div class="medium">Soon, you shall be mine!</div>
			<p>Right now it is {{ now }} </p>
        </div>

		{% if numbers %}
		<div class="yellow stuff-box">
			<p>Here are a few of my favorite numbers:</p>
			<ol start="0">
				{% for n in numbers %}
				<li>{{ n }}</li>
				{% endfor %}
			</ol>
		</div>
		{% endif %}


        <div class="blue stuff-box">
            <p class="medium">This website will enable me to meet the following goals:</p>
            <ul>
                <li>Earn lots of $$$</li>
                <li>Gather personal information from my users</li>
                <li>Get credit card numbers</li>
                <li>Sell my users out to the NSA</li>
                <li>Get my #hashtags trending on Twitter, Stumblr, Facebook</li>
            </ul>
        </div>

        <div class="yellow stuff-box">
            <p class="medium">And there is nothing you can do to stop me!!!</p>
        </div>

        <div class="white stuff-box medium">
			{{ highFiveCount }} high fives given to date - <a href="highFive">Do you want a high five?</a>
        </div>

    </body>
</html>

src/hostname/templates/hostname/index.html
{% load static %}
<head>
    <title>
        {% if "dogs" in host %}
            Man's best friend
        {% elif "cats" in host %}
            Cat's ruel teh wurld
        {% else %}
            An ordinary, innocuous web page
        {% endif %}
    </title>
    <style>

        h1 {
            text-align: center;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        {% if "dogs" in host %}
            body {
                background-color: brown;
                color: white;
            }

        {% elif "cats" in host %}
            body {
                background-color: orange;
                color: black;
            }

        {% else %}
            body {
                background-color: yellow;
                color: black;
            }

        {% endif %}
    </style>
</head>
<body>

        {% if "dogs" in host %}
            <h1>Man's best friend</h1>
            <div><img src="{% static 'hostname/yesthisisdog.jpg' %}" /></div>
        {% elif "cats" in host %}
            <h1>Cat's ruel teh wurld</h1>
            <div><img src="{% static 'hostname/grumpycat.jpg' %}" /></div>
        {% else %}
            <h1>An ordinary, innocuous web page for ordinary, innocuous people</h1>
            <div><img src="{% static 'hostname/normies.jpg' %}" /></div>
        {% endif %}
    

</body>